<?php
/**
  * @file
  * Use this module to learn about drupal's menu system
  */

/**
 * Implementation of hook_menu()
 */
function menufun_menu()
{
	$items['menufun'] = array(
		'title' => 'Greeting',
		'title callback' => 'menufun_title',
		'page callback' => 'menufun_greeting',
		'file' => 'menufun_greeting.inc',
		'page arguments' => array('Jane', 'Perez'),
		'access callback' => 'user_access',
		'access arguments' => array('receive greeting'),
		'type' => MENU_NORMAL_ITEM,
		'weight' => -1,
	);

	$items['menufun/farewell'] = array(
		'title' => 'Farewell',
		'page callback' => 'menufun_farewell',
		'file' => 'menufun_greeting.inc',
		'access callback' => 'user_access',
		'access arguments' => array('receive greeting'),
		'type' => MENU_NORMAL_ITEM,
	);

	$items['menufun/%/bar/baz'] = array(
		'title' => 'Hi',
		'page callback' => 'menufun_hello2',
		'page arguments' => array(1),
		'access callback' => TRUE,
	);

	$items['menufun/%a_zoo_animal'] = array(
		'title' => 'Hi',
		'page callback' => 'menufun_hello3',
		'page arguments' => array(1),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		'weight' => -10
	);

	return $items;
}

/**
 * Implementation of hook_permission
 */
function menufun_permission()
{
	return array(
		'receive greeting' => array(
			'title' => t('Receive a greeting'),
			'description' => t('Allows users receive a greet message'),
		),
	);
}

/**
 * Implementation of hook_menu_alter()
 */
function menufun_menu_alter(&$items)
{
	// Replace the page callback to 'user_logout' with a call to
	// our own page callback.
	$items['logout']['page callback'] = 'menu_user_logout';
	$items['logout']['access callback'] = 'user_is_logged_in';
	// Drupal no longer has to load the user.pages.inc file
	// since it will be calling our menufun_user_logout(), which
	// is in our module -- and that's already in scope.
	unset($items['logout']['file']);
}

/**
 * Menu callback
 *
 * Logs out the user and redirects it to drupal.org
 */
function menufun_user_logout()
{
	global $user;

	watchdog('menufun', 'Session closed for %name', array('%name' => $user->name));

	session_destroy();

	module_invoke_all('user', 'logout', NULL, $user);

	// Load the anonymous user so the global $user object will be correct
	// on any hook_exit() implementations.
	$user = drupal_anonymous_user();

	drupal_goto('http://drupal.org/');
}

/**
 * Implements hook_menu_link_alter()
 */
function menufun_menu_link_alter(&$item)
{
	if ($item['link_path'] == 'user/logout'){
		$item['link_title'] = 'Sign off';
	}
}

/**
 * Page callback
 */
function menufun_hello($first_name = '', $last_name = '')
{
	return t('Hello @first_name @last_name!', array('@first_name' => $first_name, '@last_name' => $last_name));
}

/**
 * Page callback
 */
 function menufun_hello2($name = NULL)
{
	return t('Hello. name is @name', array('@name' => $name));
}

/**
 * Page callback
 */
function menufun_hello3($animal)
{
	return t("Hello $animal there you");
}

function a_zoo_animal_to_arg($arg)
{
	// $arg is '%' since it is a wildcard
	// Let's replace it with a zoo animal.
	return 'tiger';
}

/**
 * Title callback
 */
function menufun_title()
{
	drupal_set_title(t('the page title'));
	$now = format_date(time());
	return t('It is now @time', array('@time' => $now));
}